import { Geist, Geist_Mono, Poppins } from 'next/font/google';
import Nav from '@/components/Nav';
import './globals.css';
import Footer from '@/components/Footer';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Poppins({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // اختار الأوزان اللي هتستخدمها
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata = {
  title: 'Mountain Matrix',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
